# Data Manipulation 

In [ ]:
- It is process of coverting data into a format that is easy to process and is more
organized 

- Data extraction from multiple sources 
- Manipulating data using python 
- Organized and readable form 


there are the popular libraries for data manipulation...

- NumPy
- Pandas
- Scipy
- Matplotlib

# Why Data Manipulation?

In [ ]:
As a Data Scientist, we gather larger volumes of data from  multiple sources.
Many times data from these sources has problem 

Problems:
    
- Missing Values 
- Incorrect format
- Different units 
- Unnecessary Data

In [ ]:
Missing Values --

- Since we are gathering the data from various multiple sources, so it might be possile that
some values in the rows are missing. 
- This  could be due to various reasons such as equipment not being available, 
user not willing to share the data etc. 

In [ ]:
Incorrect format - 

Sometimes data from different sources might be formatted differently such as having 
differnt date formats ot formats of currency etc.


In [ ]:
Different Units -

Different souces might have different units 
eg - distance ---m, mm, cm , km

In [ ]:
Unnecessary Data 

- sometimes we have a large dataset with columns that contains values that are not 
relevant to the tasks that you are performing

eg. unique id , Roll No

# NumPy

In [ ]:
NumPy - Numerical Python 

- It is a very popular library in python 
- It is used to do scientific computation and apply them to python 
applications 


In [ ]:
How will Numpy helps in Data Science?

- It is a open source Python Library 
- It is fast because it is written in C and python
- There is no inbuilt array capabilities 
- you can use list as an alternative for arrays but NumPy is better 

In [ ]:
Features of NumPy 

- It is a N- Dimensional array 
- Tools to manipulate and work with array 
- Perform mathematical and logical operations on the array 
- Powerful pre defined functions 


# Creating a Numpy Array 

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
a = np.array([1,2,3,4,5,6])
print(a)
print(id(a))

[1 2 3 4 5 6]
140679128688848


In [5]:
a = np.array([1,2,3,4,5,6])
print(a)
print(id(a))
print(type(a))

[1 2 3 4 5 6]
140679080442256
<class 'numpy.ndarray'>


In [6]:
a = np.array([1,2,3,4,5,6])
print(a)
print(id(a))
print(type(a))
print(a.ndim)

[1 2 3 4 5 6]
140679128687984
<class 'numpy.ndarray'>
1


In [7]:
a = np.array([1,'Python',3,4,5,6])
print(a)
print(id(a))
print(type(a))
print(a.ndim)

['1' 'Python' '3' '4' '5' '6']
140679128688368
<class 'numpy.ndarray'>
1


In [8]:
a = np.array([1,2,3,4,5])
print(a)
print(id(a))
print(type(a))
print(a.ndim)

[1 2 3 4 5]
140679080443216
<class 'numpy.ndarray'>
1


In [9]:
a = [1,2,3,4,5,6]
print(type(a))

<class 'list'>


In [11]:
a = np.zeros((3,4))
print(a)
print(id(a))
print(type(a))
print(a.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
140679080443216
<class 'numpy.ndarray'>
2


In [14]:
a = np.array([[1,2,3,4,5]])
print(a)
print(id(a))
print(type(a))
print(a.ndim)

[[1 2 3 4 5]]
140679124343664
<class 'numpy.ndarray'>
2


In [15]:
a = np.array([[[1,2,3,4,5]]])
print(a)
print(id(a))
print(type(a))
print(a.ndim)

[[[1 2 3 4 5]]]
140679124933488
<class 'numpy.ndarray'>
3


In [16]:
a = np.ones((3,4))
print(a)
print(id(a))
print(type(a))
print(a.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
140679124343664
<class 'numpy.ndarray'>
2


In [22]:
a = np.random.random((3,3))
print(a)

[[0.73805208 0.12768533 0.86799267]
 [0.04155493 0.20437651 0.73765103]
 [0.61773278 0.52423574 0.46846476]]


In [24]:
a = np.random.random((2,3))
print(a)

[[0.81227333 0.86815884 0.97309556]
 [0.73841708 0.05510869 0.6349889 ]]


In [25]:
a = np.random.random((1,3))
print(a)

[[0.65750405 0.3354872  0.42366381]]


In [27]:
a = np.random.random((1,2,1))
print(a)

[[[0.11925034]
  [0.70834708]]]


In [28]:
a = np.random.random((3,3,1))
print(a)

[[[0.91648263]
  [0.88201259]
  [0.45228311]]

 [[0.68417583]
  [0.14291588]
  [0.59019832]]

 [[0.08168988]
  [0.46213573]
  [0.80062546]]]


In [29]:
a = np.random.random((2,2,2))
print(a)a=np.random((2,2))

[[[0.13803787 0.88453805]
  [0.33571516 0.25058276]]

 [[0.99862149 0.67489225]
  [0.75770055 0.96057165]]]


In [ ]:
---- break 9.55 pmm

In [32]:
a=np.random.random((2,2))
print(a)

[[0.99855369 0.50966459]
 [0.10374095 0.83276468]]


In [36]:
a = np.full((2,2),4)
print(a)

[[4 4]
 [4 4]]


In [37]:
a = np.full((2,2,1),4)
print(a)

[[[4]
  [4]]

 [[4]
  [4]]]


In [39]:
a = np.full((2,3,1),5)
print(a)

[[[5]
  [5]
  [5]]

 [[5]
  [5]
  [5]]]


In [40]:
a = np.arange(10,25,5)
print(a)

[10 15 20]


In [42]:
a = np.arange(2,20,3)
print(a)

[ 2  5  8 11 14 17]


In [47]:
a = np.linspace(5,10,10)
print(a)

[ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
  8.33333333  8.88888889  9.44444444 10.        ]


In [44]:
a = np.linspace(2,100,2)
print(a)

[  2. 100.]


In [45]:
a = np.linspace(2,100,3)
print(a)

[  2.  51. 100.]


In [46]:
a = np.linspace(2,100,40)
print(a)

[  2.           4.51282051   7.02564103   9.53846154  12.05128205
  14.56410256  17.07692308  19.58974359  22.1025641   24.61538462
  27.12820513  29.64102564  32.15384615  34.66666667  37.17948718
  39.69230769  42.20512821  44.71794872  47.23076923  49.74358974
  52.25641026  54.76923077  57.28205128  59.79487179  62.30769231
  64.82051282  67.33333333  69.84615385  72.35897436  74.87179487
  77.38461538  79.8974359   82.41025641  84.92307692  87.43589744
  89.94871795  92.46153846  94.97435897  97.48717949 100.        ]


In [49]:
a = np.array([1,2,3,4,5])
print(a)
print(id(a))
print(type(a))
print(a.ndim)
print(a.shape)

[1 2 3 4 5]
140679124340784
<class 'numpy.ndarray'>
1
(5,)


In [51]:
a  = np.array([[1,2,3], [4,5,6]])
print(a)
print()
print(id(a))
print(type(a))
print(a.ndim)
print(a.shape)


[[1 2 3]
 [4 5 6]]

140679133355440
<class 'numpy.ndarray'>
2
(2, 3)


In [56]:
a = np.array([[1,2,3],[5,6,7]])
print(a)
print()
a.shape=(3,2)
print(a)

[[1 2 3]
 [5 6 7]]

[[1 2]
 [3 5]
 [6 7]]


In [58]:
a = np.arange(24)
print(a)
print(a.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
24


In [59]:
a = np.arange(1,24,3)
print(a)
print(a.size)

[ 1  4  7 10 13 16 19 22]
8


In [62]:
a = np.arange(24)
print(a)
print(a.size)
print(a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
24
int64


In [63]:
a = np.arange(24, dtype = float)
print(a)
print(a.size)
print(a.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]
24
float64


In [71]:
a = np.arange(24, dtype = float)
print(a)
print(a.size)
print(a.dtype)
print()
b = a.reshape(3,4,2)
print(b)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]
24
float64

[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]
  [ 6.  7.]]

 [[ 8.  9.]
  [10. 11.]
  [12. 13.]
  [14. 15.]]

 [[16. 17.]
  [18. 19.]
  [20. 21.]
  [22. 23.]]]


In [72]:
np.sum([10,20])

30

In [73]:
a,b = 10,20 
np.sum([a,b])

30

In [80]:
np.sum([[0,1,6],[0,5,3]], axis = 0)

array([0, 6, 9])

In [82]:
np.sum([[1,1,6], [0,5,2]], axis = 1)

array([8, 7])

In [90]:
a = [1,2,3,4,5]
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.corrcoef(a))
print(np.std(a))


15
1
5
3.0
3.0
1.0
1.4142135623730951


In [91]:
a = [1,2,4]
b = [2,4,4]
np.equal(a,b)

array([False, False,  True])

In [94]:
a = [1,2,4]
b = [1,3,4]
np.array_equal(a,b)

False

In [96]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [97]:
arr[0]

1

In [98]:
arr[:2]

array([1, 2])

In [99]:
a = [1,2,4]
b = [2,4,4]
np.equal(a,b)

array([False, False,  True])